<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionRoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Insert some stuff
	DB::table('permission_role')->insert(
		array(
			array('id' => '1','permission_id' => '1','role_id' => '1'),
			array('id' => '2','permission_id' => '2','role_id' => '1'),
			array('id' => '3','permission_id' => '3','role_id' => '1'),
			array('id' => '4','permission_id' => '4','role_id' => '1'),
			array('id' => '5','permission_id' => '5','role_id' => '1'),
			array('id' => '6','permission_id' => '6','role_id' => '1'),
			array('id' => '7','permission_id' => '7','role_id' => '1'),
			array('id' => '8','permission_id' => '8','role_id' => '1'),
			array('id' => '9','permission_id' => '9','role_id' => '1'),
			array('id' => '10','permission_id' => '10','role_id' => '1'),
			array('id' => '11','permission_id' => '11','role_id' => '1'),
			array('id' => '12','permission_id' => '12','role_id' => '1'),
			array('id' => '13','permission_id' => '13','role_id' => '1'),
			array('id' => '14','permission_id' => '14','role_id' => '1'),
			array('id' => '15','permission_id' => '15','role_id' => '1'),
			array('id' => '16','permission_id' => '16','role_id' => '1'),
			array('id' => '17','permission_id' => '17','role_id' => '1'),
			array('id' => '18','permission_id' => '18','role_id' => '1'),
			array('id' => '19','permission_id' => '19','role_id' => '1'),
			array('id' => '20','permission_id' => '20','role_id' => '1'),
			array('id' => '21','permission_id' => '21','role_id' => '1'),
			array('id' => '22','permission_id' => '22','role_id' => '1'),
			array('id' => '23','permission_id' => '23','role_id' => '1'),
			array('id' => '24','permission_id' => '24','role_id' => '1'),
			array('id' => '25','permission_id' => '25','role_id' => '1'),
			array('id' => '26','permission_id' => '26','role_id' => '1'),
			array('id' => '27','permission_id' => '27','role_id' => '1'),
			array('id' => '28','permission_id' => '28','role_id' => '1'),
			array('id' => '29','permission_id' => '29','role_id' => '1'),
			array('id' => '30','permission_id' => '30','role_id' => '1'),
			array('id' => '31','permission_id' => '31','role_id' => '1'),
			array('id' => '32','permission_id' => '32','role_id' => '1'),
			array('id' => '33','permission_id' => '33','role_id' => '1'),
			array('id' => '34','permission_id' => '34','role_id' => '1'),
			array('id' => '35','permission_id' => '35','role_id' => '1'),
			array('id' => '36','permission_id' => '36','role_id' => '1'),
			array('id' => '37','permission_id' => '37','role_id' => '1'),
			array('id' => '38','permission_id' => '38','role_id' => '1'),
			array('id' => '39','permission_id' => '39','role_id' => '1'),
			array('id' => '40','permission_id' => '40','role_id' => '1'),
			array('id' => '41','permission_id' => '41','role_id' => '1'),
			array('id' => '42','permission_id' => '42','role_id' => '1'),
			array('id' => '43','permission_id' => '43','role_id' => '1'),
			array('id' => '44','permission_id' => '44','role_id' => '1'),
			array('id' => '45','permission_id' => '45','role_id' => '1'),
			array('id' => '46','permission_id' => '46','role_id' => '1'),
			array('id' => '47','permission_id' => '47','role_id' => '1'),
			array('id' => '48','permission_id' => '48','role_id' => '1'),
			array('id' => '49','permission_id' => '49','role_id' => '1'),
			array('id' => '50','permission_id' => '50','role_id' => '1'),
			array('id' => '51','permission_id' => '51','role_id' => '1'),
			array('id' => '52','permission_id' => '52','role_id' => '1'),
			array('id' => '53','permission_id' => '53','role_id' => '1'),
			array('id' => '54','permission_id' => '54','role_id' => '1'),
			array('id' => '55','permission_id' => '55','role_id' => '1'),
			array('id' => '56','permission_id' => '56','role_id' => '1'),
			array('id' => '57','permission_id' => '57','role_id' => '1'),
			array('id' => '58','permission_id' => '58','role_id' => '1'),
			array('id' => '59','permission_id' => '59','role_id' => '1'),
			array('id' => '60','permission_id' => '60','role_id' => '1'),
			array('id' => '61','permission_id' => '61','role_id' => '1'),
			array('id' => '62','permission_id' => '62','role_id' => '1'),
			array('id' => '63','permission_id' => '63','role_id' => '1'),
			array('id' => '64','permission_id' => '64','role_id' => '1'),
			array('id' => '65','permission_id' => '65','role_id' => '1'),
			array('id' => '66','permission_id' => '66','role_id' => '1'),
			array('id' => '67','permission_id' => '67','role_id' => '1'),
			array('id' => '68','permission_id' => '68','role_id' => '1'),
			array('id' => '69','permission_id' => '69','role_id' => '1'),
			array('id' => '70','permission_id' => '70','role_id' => '1'),
			array('id' => '72','permission_id' => '72','role_id' => '1'),
			array('id' => '73','permission_id' => '73','role_id' => '1'),
			array('id' => '74','permission_id' => '74','role_id' => '1'),
			array('id' => '75','permission_id' => '75','role_id' => '1'),
			array('id' => '76','permission_id' => '76','role_id' => '1'),
			array('id' => '77','permission_id' => '77','role_id' => '1'),
			array('id' => '78','permission_id' => '78','role_id' => '1'),
			array('id' => '79','permission_id' => '79','role_id' => '1'),
			array('id' => '80','permission_id' => '80','role_id' => '1'),
			array('id' => '81','permission_id' => '81','role_id' => '1'),
			array('id' => '82','permission_id' => '82','role_id' => '1'),
			array('id' => '83','permission_id' => '83','role_id' => '1'),
			array('id' => '84','permission_id' => '84','role_id' => '1'),
			array('id' => '85','permission_id' => '85','role_id' => '1'),
			array('id' => '86','permission_id' => '86','role_id' => '1'),
			array('id' => '87','permission_id' => '87','role_id' => '1'),
			array('id' => '88','permission_id' => '88','role_id' => '1'),
			array('id' => '89','permission_id' => '89','role_id' => '1'),
			array('id' => '90','permission_id' => '90','role_id' => '1'),
			array('id' => '91','permission_id' => '91','role_id' => '1'),
			array('id' => '92','permission_id' => '92','role_id' => '1'),
			array('id' => '93','permission_id' => '93','role_id' => '1'),
			array('id' => '94','permission_id' => '1','role_id' => '2'),
			array('id' => '95','permission_id' => '2','role_id' => '2'),
			array('id' => '96','permission_id' => '3','role_id' => '2'),
			array('id' => '97','permission_id' => '5','role_id' => '2'),
			array('id' => '98','permission_id' => '4','role_id' => '2'),
			array('id' => '99','permission_id' => '7','role_id' => '2'),
			array('id' => '100','permission_id' => '6','role_id' => '2'),
			array('id' => '101','permission_id' => '9','role_id' => '2'),
			array('id' => '102','permission_id' => '8','role_id' => '2'),
			array('id' => '103','permission_id' => '11','role_id' => '2'),
			array('id' => '104','permission_id' => '13','role_id' => '2'),
			array('id' => '105','permission_id' => '12','role_id' => '2'),
			array('id' => '106','permission_id' => '14','role_id' => '2'),
			array('id' => '107','permission_id' => '10','role_id' => '2'),
			array('id' => '108','permission_id' => '87','role_id' => '2'),
			array('id' => '109','permission_id' => '20','role_id' => '2'),
			array('id' => '110','permission_id' => '19','role_id' => '2'),
			array('id' => '111','permission_id' => '28','role_id' => '2'),
			array('id' => '112','permission_id' => '27','role_id' => '2'),
			array('id' => '113','permission_id' => '86','role_id' => '2'),
			array('id' => '114','permission_id' => '30','role_id' => '2'),
			array('id' => '115','permission_id' => '29','role_id' => '2'),
			array('id' => '116','permission_id' => '32','role_id' => '2'),
			array('id' => '117','permission_id' => '31','role_id' => '2'),
			array('id' => '118','permission_id' => '34','role_id' => '2'),
			array('id' => '119','permission_id' => '33','role_id' => '2'),
			array('id' => '120','permission_id' => '40','role_id' => '2'),
			array('id' => '121','permission_id' => '39','role_id' => '2'),
			array('id' => '122','permission_id' => '42','role_id' => '2'),
			array('id' => '123','permission_id' => '41','role_id' => '2'),
			array('id' => '124','permission_id' => '52','role_id' => '2'),
			array('id' => '125','permission_id' => '51','role_id' => '2'),
			array('id' => '126','permission_id' => '54','role_id' => '2'),
			array('id' => '127','permission_id' => '53','role_id' => '2'),
			array('id' => '128','permission_id' => '56','role_id' => '2'),
			array('id' => '129','permission_id' => '55','role_id' => '2'),
			array('id' => '130','permission_id' => '58','role_id' => '2'),
			array('id' => '131','permission_id' => '57','role_id' => '2'),
			array('id' => '132','permission_id' => '60','role_id' => '2'),
			array('id' => '133','permission_id' => '59','role_id' => '2'),
			array('id' => '134','permission_id' => '69','role_id' => '2'),
			array('id' => '135','permission_id' => '68','role_id' => '2'),
			array('id' => '136','permission_id' => '67','role_id' => '2'),
			array('id' => '137','permission_id' => '66','role_id' => '2'),
			array('id' => '138','permission_id' => '63','role_id' => '2'),
			array('id' => '139','permission_id' => '64','role_id' => '2'),
			array('id' => '140','permission_id' => '65','role_id' => '2'),
			array('id' => '141','permission_id' => '81','role_id' => '2'),
			array('id' => '142','permission_id' => '80','role_id' => '2'),
			array('id' => '143','permission_id' => '78','role_id' => '2'),
			array('id' => '144','permission_id' => '79','role_id' => '2'),
			array('id' => '145','permission_id' => '77','role_id' => '2'),
			array('id' => '146','permission_id' => '76','role_id' => '2'),
			array('id' => '147','permission_id' => '75','role_id' => '2'),
			array('id' => '148','permission_id' => '74','role_id' => '2'),
			array('id' => '149','permission_id' => '73','role_id' => '2'),
			array('id' => '150','permission_id' => '70','role_id' => '2'),
			array('id' => '151','permission_id' => '72','role_id' => '2'),
			array('id' => '152','permission_id' => '85','role_id' => '2'),
			array('id' => '153','permission_id' => '84','role_id' => '2')
		)
	);
    }
}
